# Generated by Django 5.2.3 on 2025-07-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Koffinoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_image/'),
        ),
    ]
