# Generated by Django 5.2.3 on 2025-07-24 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Koffinoor', '0005_guestreview_delete_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('coffee_item', models.CharField(blank=True, max_length=50, null=True)),
                ('coffee_qty', models.PositiveIntegerField(default=0)),
                ('tea_item', models.CharField(blank=True, max_length=50, null=True)),
                ('tea_qty', models.PositiveIntegerField(default=0)),
                ('shake_item', models.CharField(blank=True, max_length=50, null=True)),
                ('shake_qty', models.PositiveIntegerField(default=0)),
                ('snack_item', models.CharField(blank=True, max_length=50, null=True)),
                ('snack_qty', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(default='UPI', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment',
        ),
    ]
