# Generated by Django 5.2.1 on 2026-06-30 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Koffinoor', '0006_order_review_remove_orders_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='GuestReview',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coffee_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coffee_qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shake_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shake_qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='snack_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='snack_qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tea_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tea_qty',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Koffinoor.order'),
        ),
    ]
